COLLAB:
  acc: 78.8+-1.5
  agg: Max
  alpha: 0.6
  epochs: 50
  hidden: 512
  layer: 2
  lr: 1e-5
  out_hidden: 64
  w: 1e-5
  warmup: 100
DD:
  acc: 78.61+-4.3
  alpha: 0.5
  epochs: 50
  hidden: 512
  layer: 3
  lr: 1e-4
  out_hidden: 64
  rate: 0.4
  w: 1e-5
  warmup: 100
ENZYMES:
  alpha: 0.8
  epochs: 100
  hidden: 512
  layer: 2
  lr: 1e-4
  out_hidden: 64
  rate: 0.1
  w: 1e-5
  warmup: 100
IMDB-BINARY:
  acc: 74.8+-4.7
  alpha: 0.2
  epochs: 100
  hidden: 512
  layer: 2
  lr: 1e-5
  out_hidden: 64
  w: 5e-4
  warmup: 100
IMDB-MULTI:
  acc: 50.8+-1.65
  agg: Max
  alpha: 0.5
  epochs: 200
  hidden: 512
  layer: 1
  lr: 1e-5
  out_hidden: 64
  w: 1e-5
  warmup: 100
MUTAG:
  acc: 0.8994152046783626
  alpha: 0.17717860906319477
  contrast_with_central_nodes: 0
  depth: 5
  epochs: 100
  hidden: 512
  layer: 1
  lr: 1e-4
  rate: 0.07200000000000001
  ring_width: 2.0
  w: 1e-06
  warmup: 61.39677578223307
NCI1:
  acc: 80.97+-2.7
  alpha: 0.5
  epochs: 20
  hidden: 512
  layer: 3
  lr: 1e-5
  out_hidden: 64
  w: 1e-4
  warmup: 100
NCI109:
  acc: 0.8005853452126284
  alpha: 0.1815153326691898
  contrast_with_central_nodes: 1
  depth: 14
  epochs: 740.0
  hidden: 512
  layer: 2
  lr: 1
  rate: 0.036000000000000004
  ring_width: 15.0
  w: 2
  warmup: 47.43640631891315
PROTEINS:
  acc: 0.7591457528957529
  alpha: 0.8081696131783881
  contrast_with_central_nodes: 1
  depth: 9
  epochs: 0
  hidden: 0
  layer: 1
  lr: 0
  rate: 0.04
  ring_width: 9.0
  w: 1
  warmup: 53.66052774577925
PTC_MR:
  acc: 0.645546218487395
  alpha: 0.39552927771225105
  contrast_with_central_nodes: 1
  depth: 14
  epochs: 440.0
  hidden: 0
  layer: 2
  lr: 1
  rate: 0.056
  ring_width: 14.0
  w: 0
  warmup: 120.85189437848325
REDDIT-BINARY:
  acc: 55.17+-8.4,0.7
  alpha: 0.5
  epochs: 100
  hidden: 512
  layer: 2
  lr: 1e-3
  out_hidden: 64
  w: 1e-5
  warmup: 100
REDDIT-MULTI-5K:
  acc: 55.17+-8.4,0.7
  alpha: 0.5
  epochs: 100
  hidden: 512
  layer: 2
  lr: 1e-3
  out_hidden: 64
  w: 1e-5
  warmup: 100
facebook_ct1:
  acc: null
  alpha: 0.2
  epochs: 100
  hidden: 512
  layer: 2
  lr: 1e-5
  out_hidden: 64
  w: 5e-4
  warmup: 100
mit_ct1:
  acc: null
  alpha: 0.2
  epochs: 100
  hidden: 512
  layer: 2
  lr: 1e-5
  out_hidden: 64
  w: 5e-4
  warmup: 100
mydata:
  acc: 80.2+-1.9
  alpha: 0.3
  epochs: 100
  featdim: 256
  hidden: 512
  layer: 2
  lr: 1e-5
  out_hidden: 64
  rate: 0.2
  w: 1e-5
  warmup: 100
